### PR TITLE
Rename shear_strain to deviatoric_strain

### PR DESCRIPTION
**Pull request by KeitaNakamura**
I don't know why I have used `shear_strain` until now, but I just renamed `shear_strain` to `deviatoric_strain` to control `ϵ[1,1] - ϵ[3,3]` in this PR. I think that the shear strain should be `2ϵ[i,j]` where `i ≠ j`. Am I correct, @veerayut?

### CODE REVIEW

**Comment by veerayut** [comment]
I have never used both shear and deviator strains-controlled as well.

However, it might be useful in the future.

Regarding shear strain, "2ϵ[i,j] where i ≠ j" is correct.

**Comment by KeitaNakamura** [comment]
So, consequently, I'm going to use following names:
* `deviatoric_strain`: `ϵ[1,1] - ϵ[3,3]` in the triaxial condition.
* `shear_strain`: `2ϵ[i, j]` where `i ≠ j` (simple shear test. this is used only for `volume_constant`?)
* `deviatoric_stress`: `ϵ[1,1] - ϵ[3,3]` in the triaxial condition.
* `shear_stress`: `σ[2,3]` where `i ≠ j` (this is used only for `volume_constant` as well as `shear_strain`?).

Do you agree with this?

**Comment by veerayut** [comment]
I agrees with you. Please feel free to change.

Regarding shear strain, please explain me later when you come back here,
Why does it work only for volume_constant case?

Thank you

**Comment by KeitaNakamura** [comment]
Actually, I have no idea about that. Is there any conditions in simple shear test? I just don't know much about experiments.

**Comment by veerayut** [comment]
I remembers that there are drained and undrained conditions in simple shear test. However, I am also not sure much about it.

**Pull request merged**
